name: New version check
on:
  workflow_dispatch:
  schedule:
  - cron: 0 16 * * 5
  push:
    branches:
      - main

jobs:
  check:
    name: Check new version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Get old Version from Makefile
        id: get_makefile_old_version
        if: always()
        run: |
          MAKEFILE_PATH="${{ github.workspace }}/Makefile"
          if [ -f "$MAKEFILE_PATH" ]; then
            VERSION=$(grep "PKG_VERSION:=" "$MAKEFILE_PATH" | cut -d'=' -f2 | tr -d ' "')
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "found=true" >> $GITHUB_OUTPUT
          else
            echo "found=false" >> $GITHUB_OUTPUT
          fi

      - uses: EkkoG/openwrt-packages-version-checker@main
        env:
          COMMIT_TOKEN: ${{ secrets.OWRT_PACKAGE_RELEASE_TOKEN }}
          REPO: CSoellinger/gpio-fan-rpm
          BRANCH: main
          SOURCE_URL: https://codeload.github.com/CSoellinger/gpio-fan-rpm/tar.gz/refs/tags/v{{version}}?

      - name: Get Version from Makefile
        id: get_makefile_version
        if: always()
        run: |
          MAKEFILE_PATH="${{ github.workspace }}/Makefile"
          if [ -f "$MAKEFILE_PATH" ]; then
            VERSION=$(grep "PKG_VERSION:=" "$MAKEFILE_PATH" | cut -d'=' -f2 | tr -d ' "')
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "found=true" >> $GITHUB_OUTPUT
          else
            echo "found=false" >> $GITHUB_OUTPUT
          fi

      # - name: Create and Push Tag
      #   if: steps.get_makefile_old_version.outputs.version != steps.get_makefile_version.outputs.version
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.OWRT_PACKAGE_RELEASE_TOKEN }}
      #   run: |
      #     NEW_VER="${{ steps.get_makefile_version.outputs.version }}"
      #     TAG_NAME="v$NEW_VER"

      #     echo "üöÄ New version: $NEW_VER. Create tag $TAG_NAME..."

      #     git config user.name "github-actions[bot]"
      #     git config user.email "github-actions[bot]@users.noreply.github.com"

      #     if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
      #       echo "‚ö†Ô∏è Tag $TAG_NAME already exists. Skip."
      #     else
      #       git tag "$TAG_NAME"
      #       git push origin "$TAG_NAME"
      #       echo "‚úÖ Tag $TAG_NAME succesfully pushed."
      #     fi
