name: New version check
on:
  workflow_dispatch:
  schedule:
  - cron: 0 16 * * 5
  push:
    branches:
      - main

jobs:
  check:
    name: Check new version
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: EkkoG/openwrt-packages-version-checker@main
        env:
          COMMIT_TOKEN: ${{ secrets.OWRT_PACKAGE_RELEASE_TOKEN }}
          REPO: CSoellinger/gpio-fan-rpm
          BRANCH: main
          SOURCE_URL: https://codeload.github.com/CSoellinger/gpio-fan-rpm/tar.gz/refs/tags/{{version}}?
